### ISSUE TITLE
the pip command no longer works

### ISSUE THREAD

**Issue by Yu-Yunfeng** [mara/data-integration#15]

**Comment by guzmud** [comment]
Requirements : python3.6 and git itself

```bash
pip3.6 install --process-dependency-links git+https://github.com/mara/mara-page.git
pip3.6 install --process-dependency-links git+https://github.com/mara/mara-db.git
pip3.6 install --process-dependency-links git+https://github.com/mara/data-integration.git
```

Is it enough?

**Comment by martin-loetzsch** [comment]
It works again. We were relying on the `--process-dependency-links` feature of pip, which recently [got removed](https://github.com/pypa/pip/issues/6162).

We solved it now by uploading the mara dependencies to PyPi.

Still, in a project it might me better to pin down the dependencies explicitly, as in [https://github.com/mara/mara-example-project/blob/master/requirements.txt](https://github.com/mara/mara-example-project/blob/master/requirements.txt).
