### ISSUE TITLE
Is there any way to deal with errors/exceptions raised in the pipeline tasks?

### ISSUE THREAD

**Issue by cmollis** [mara/data-integration#3]
I realize that these are just shell scripts.. but not clear how to manage errors (some of which may invalidate the remaining tasks).  Otherwise.. pretty cool.

**Comment by cmollis** [comment]
wait.. so the shell script should return a 1 or FALSE or set some exit code.. will this cancel the pipeline?  It looks like run() will return false if the shell command returns false

**Comment by martin-loetzsch** [comment]
Yes, the behavior is the following:

A `Task` fails as soon as one of it's `Commands` fails (https://github.com/mara/data-integration/blob/master/data_integration/pipelines.py#L102). 

This by default means that the shell command of a `Command` returned a non-zero exit code (https://github.com/mara/data-integration/blob/master/data_integration/pipelines.py#L66).

When a `Task` fails, the pipeline execution waits until all currently running Task finish (https://github.com/mara/data-integration/blob/master/data_integration/execution.py#L135)

We still need to implement a "continue on error" behavior for pipelines, see #6
