### ISSUE TITLE
Q: feasibility of substituting pgsql for sqlite?  

### ISSUE THREAD

**Issue by marks** [mara/data-integration#4]
More of a question than an issue.. but maybe it could turn into a PR :) 

Is it easy/hard/impossible/a good idea/a bad idea to substitute postgres for sqlite? This looks really cool and promising but I'm interested in reducing external (or local -- this is going to be dockerized) dependencies

Thanks in advance!

**Comment by jankatins** [comment]
Re feasibility: The main idea is to load data into the db with `something_outputting_csv | psql_command_which_inputs_csv_into_db` and to run pipelines as `cat sql_file | psql ...` to run sql commands on a db. As long as this is supported, I think it can be made to work with other DBs. It might be that some SQL commands are not available (e.g. UPSERT, needed for incremental loads), but that can probably be worked around.

That being said: currently a lot of internal stuff simply assumes that the backend is a postgresql DB. Lot's of internal stuff like [incremental loading](https://github.com/mara/data-integration/blob/master/data_integration/commands/sql.py#L235) would need to be abstracted (e.g. similar to the `copy_*` stuff which uses `@single_dispatch`: https://github.com/mara/mara-db/blob/master/mara_db/shell.py).

I've no clue if the above requirements are possible in sqlite, but e.g. SQL Server does not really support piping csv into a DB.

**Comment by martin-loetzsch** [comment]
There's two aspects to this: 

1 .The ETL needs a number of book keeping tables 

- for run-time stats, run output and system statistics (https://github.com/mara/data-integration/blob/master/data_integration/logging/run_log.py)

- for incremental loading from databases (https://github.com/mara/data-integration/blob/master/data_integration/incremental_processing/incremental_copy_status.py)

- for incremental processing (https://github.com/mara/data-integration/blob/master/data_integration/incremental_processing/file_dependencies.py)

Making these tables work with SQlite is quite hard (SQlite doesn't have arrays) and I'd be also afraid of performance impacts.

2. For the actual ETL itself, any database can be used. As @jankatins explained, it boils down to extending https://github.com/mara/mara-db/blob/master/mara_db/shell.py


So the PostgreSQL dependency will stay for now, and we are working on dockerization.
