### ISSUE TITLE
PostgreSQLDB(..) constructor doesn't handle port

### ISSUE THREAD

**Issue by bloo** [mara/data-integration#9]
Passing a port (as an int or a string) isn't honored as it runs against `5432` no matter what you pass in to the constructor.

```
mara_db.config.databases \
    = lambda: {'mara': mara_db.dbs.PostgreSQLDB(host='localhost', port=25432, user='etl', password='etl', database='etl')}
```

**Comment by bloo** [comment]
Follow up - this works for configuring access during run but fails during migration - it's the migration code that does not honor the port:

```
import mara_db.auto_migration
...
mara_db.auto_migration.auto_discover_models_and_migrate()

```

**Comment by martin-loetzsch** [comment]
If the problem still exists, please update mara_db package
